In [103]:
import pandas as pd

In [104]:
import numpy as np

In [105]:
from sklearn.feature_selection import VarianceThreshold

In [114]:
vt = VarianceThreshold(threshold = 0.2)

In [115]:
import pandas as pd
df = pd.DataFrame({'A':['m','f','m','m','m','m','m','m'], 
              'B':[1,2,3,1,2,1,1,1], 
              'C':[1,2,3,1,2,1,1,1]})

In [116]:
df

A  B  C
0  m  1  1
1  f  2  2
2  m  3  3
3  m  1  1
4  m  2  2
5  m  1  1
6  m  1  1
7  m  1  1

In [117]:
from sklearn.preprocessing import OrdinalEncoder

In [118]:
oe = OrdinalEncoder()

In [119]:
df['A'] = oe.fit_transform(df[['A']])

In [120]:
df

A  B  C
0  1.0  1  1
1  0.0  2  2
2  1.0  3  3
3  1.0  1  1
4  1.0  2  2
5  1.0  1  1
6  1.0  1  1
7  1.0  1  1

In [121]:
vt.fit_transform(df)

array([[1., 1., 1.],
       [0., 2., 2.],
       [1., 3., 3.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [122]:
vt.variances_

array([0.109375, 0.5     , 0.5     ])

In [1]:
import pandas as pd


In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/winequality-white.csv', sep=';')


In [2]:
df.head()

NameError: name 'df' is not defined

In [128]:
corr = df.corr(method='pearson')

In [68]:
import numpy as np

In [129]:
np.abs(corr.loc['fixed acidity']).sort_values(ascending=False)[:6]

fixed acidity    1.000000
pH               0.425858
citric acid      0.289181
density          0.265331
alcohol          0.120881
quality          0.113663
Name: fixed acidity, dtype: float64

# CHi Square Method

In [23]:
import pandas as pd

In [24]:
from sklearn.feature_selection import chi2, SelectKBest

In [27]:
adult_data = pd.read_csv('D:\\learning\\ml\\adult.csv')

In [28]:
adult_data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [34]:

cat_adult_data = adult_data.select_dtypes(include=['object'])

In [35]:
cat_adult_data

workclass     education      marital-status         occupation  \
0           Private          11th       Never-married  Machine-op-inspct   
1           Private       HS-grad  Married-civ-spouse    Farming-fishing   
2         Local-gov    Assoc-acdm  Married-civ-spouse    Protective-serv   
3           Private  Some-college  Married-civ-spouse  Machine-op-inspct   
4                 ?  Some-college       Never-married                  ?   
...             ...           ...                 ...                ...   
48837       Private    Assoc-acdm  Married-civ-spouse       Tech-support   
48838       Private       HS-grad  Married-civ-spouse  Machine-op-inspct   
48839       Private       HS-grad             Widowed       Adm-clerical   
48840       Private       HS-grad       Never-married       Adm-clerical   
48841  Self-emp-inc       HS-grad  Married-civ-spouse    Exec-managerial   

      relationship   race  gender native-country income  
0        Own-child  Black    Male  United-States  <=50K  
1          Husband  White    Male  United-States  <=50K  
2          Husband  White    Male  United-States   >50K  
3          Husband  Black    Male  United-States   >50K  
4        Own-child  White  Female  United-States  <=50K  
...            ...    ...     ...            ...    ...  
48837         Wife  White  Female  United-States  <=50K  
48838      Husband  White    Male  United-States   >50K  
48839    Unmarried  White  Female  United-States  <=50K  
48840    Own-child  White    Male  United-States  <=50K  
48841         Wife  White  Female  United-States   >50K  

[48842 rows x 9 columns]

In [43]:
from sklearn.preprocessing import OrdinalEncoder

In [44]:
oe = OrdinalEncoder()

In [45]:
data_td = oe.fit_transform(cat_adult_data)

In [46]:
data_td

array([[ 4.,  1.,  4., ...,  1., 39.,  0.],
       [ 4., 11.,  2., ...,  1., 39.,  0.],
       [ 2.,  7.,  2., ...,  1., 39.,  1.],
       ...,
       [ 4., 11.,  6., ...,  0., 39.,  0.],
       [ 4., 11.,  4., ...,  1., 39.,  0.],
       [ 5., 11.,  2., ...,  0., 39.,  1.]])

In [47]:
columns=list(cat_adult_data.columns.values)

In [48]:
columns

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native-country',
 'income']

In [41]:
df = pd.DataFrame(data_td, columns=list(cat_adult_data.columns.values))

In [54]:
df.head()

workclass  education  marital-status  occupation  relationship  race  \
0        4.0        1.0             4.0         7.0           3.0   2.0   
1        4.0       11.0             2.0         5.0           0.0   4.0   
2        2.0        7.0             2.0        11.0           0.0   4.0   
3        4.0       15.0             2.0         7.0           0.0   2.0   
4        0.0       15.0             4.0         0.0           3.0   4.0   

   gender  native-country  income  
0     1.0            39.0     0.0  
1     1.0            39.0     0.0  
2     1.0            39.0     1.0  
3     1.0            39.0     1.0  
4     0.0            39.0     0.0

In [62]:
chi_2, pval = chi2(df.drop(columns=['income']), df.income)

In [63]:
chi_2

array([  75.06529643,  457.11744177, 1680.12355508,  782.22653822,
       5569.46092253,   47.94991574,  745.88760863,   11.97849255])

In [65]:
feature_importances = pd.Series(chi_2, index=list(df.drop(columns=['income']).columns.values))

In [66]:
feature_importances.sort_values(ascending=False)[:4]

relationship      5569.460923
marital-status    1680.123555
occupation         782.226538
gender             745.887609
dtype: float64

In [67]:
df[list(feature_importances.sort_values(ascending=False)[:4].index)][:5]

relationship  marital-status  occupation  gender
0           3.0             4.0         7.0     1.0
1           0.0             2.0         5.0     1.0
2           0.0             2.0        11.0     1.0
3           0.0             2.0         7.0     1.0
4           3.0             4.0         0.0     0.0

# Using SelectKBest

In [68]:
fs = SelectKBest(k=4, score_func=chi2)

In [69]:
fs

SelectKBest(k=4, score_func=<function chi2 at 0x1B2DFA50>)

In [71]:
fs.fit_transform(df.drop(columns=['income']), df.income)

array([[ 4.,  7.,  3.,  1.],
       [ 2.,  5.,  0.,  1.],
       [ 2., 11.,  0.,  1.],
       ...,
       [ 6.,  1.,  4.,  0.],
       [ 4.,  1.,  3.,  1.],
       [ 2.,  4.,  5.,  0.]])

In [72]:
fs.scores_

array([  75.06529643,  457.11744177, 1680.12355508,  782.22653822,
       5569.46092253,   47.94991574,  745.88760863,   11.97849255])

# Univariate Test (Anova)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/winequality-white.csv', sep=';')


In [5]:
from sklearn.feature_selection import f_classif, SelectKBest
fs = SelectKBest(k=8,score_func=f_classif)

In [6]:
fs

SelectKBest(k=8)

In [7]:
feature_data = fs.fit_transform(df.drop(columns=['quality']), df.quality)

In [8]:
feature_data

array([[  7.     ,   0.27   ,  20.7    , ..., 170.     ,   1.001  ,
          8.8    ],
       [  6.3    ,   0.3    ,   1.6    , ..., 132.     ,   0.994  ,
          9.5    ],
       [  8.1    ,   0.28   ,   6.9    , ...,  97.     ,   0.9951 ,
         10.1    ],
       ...,
       [  6.5    ,   0.24   ,   1.2    , ..., 111.     ,   0.99254,
          9.4    ],
       [  5.5    ,   0.29   ,   1.1    , ..., 110.     ,   0.98869,
         12.8    ],
       [  6.     ,   0.21   ,   0.8    , ...,  98.     ,   0.98941,
         11.8    ]])

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
lr = LogisticRegression()

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
trainX, testX, trainY, testY = train_test_split(feature_data, df.quality)

In [13]:
lr.fit(trainX, trainY)

c:\python37-32\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [14]:
lr.score(testX,testY)

0.4775510204081633

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
dt = DecisionTreeClassifier()

In [17]:
dt.fit(trainX, trainY)

DecisionTreeClassifier()

In [18]:
dt.score(testX,testY)

0.5853061224489796